terrain: "MultipleSlopes"
# Options: Flat, Step, Rough, SineLowFreq, SineHighFreq, SlopePlat, Gap, TwoSlope, MultipleSlopes, TwoStep
run_derivative_test: false
plot_trajectory: false
play_initialization: false
shift_initialization: true
init_state_from_file: true  # 'true' if initial_pose for base is read from this file, 'false' if it is set by the current anymal state

constrain_initial_y_base: true
constrain_final_y_base:   false 
constrain_final_z_base:   false
constrain_final_ee_pos:   false
constrain_final_base_orientation: true

Flat:
# 0.5m, 3s
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.41
   
  final_pose: 
    x: 2.0
    y: 0.0
    z: 0.41

  total_time: 8.0
  use_wheels_motion_constraint: false
  traction_limit: 100.0 #30.0

Step:
# slope 1 up, no shift, 1.8, 0.65, 3s, 200N, tt
# slope 1 down, no shift, -1.8, 0.45, 3s, 200N, tt
# slope 2 up, shift, 1.7, 0.65, 3.5s, 300N, ff
# slope 2 up, shift, 1.7, 0.65, 4.2s, 400N, ff (also works)
# slope 2 down, shift, -1.7, 0.45, 4.5s, 300N, ff
# slope 2 up near, shift, 1.2, 0.65, 2.4s, 300N, ff
# slope 2 down near, shift, -1.2, 0.45, 2.4s, 300N, ff
# slope 1 up near, shift, 1.2, 0.65, 2.4s, 300N, ff

# slope 65 up, shift, 1.8, 0.65, 3.4s, 200N, ff -> ok, but no convergence

  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.41
   
  final_pose: 
    x: 1.8
    y: 0.0
    z: 0.61

  total_time: 3.5
  use_wheels_motion_constraint: false
  traction_limit: 300.0

Rough:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.4
   
  final_pose: 
    x: 4.0
    y: 0.0
    z: 0.9

  total_time: 3.5
  use_wheels_motion_constraint: false
  traction_limit: 30.0

SineHighFreq:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 4.0
    y: 0.0
    z: 0.5

  total_time: 4.0
  use_wheels_motion_constraint: false
  traction_limit: 30.0

SineLowFreq:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.6
   
  final_pose: 
    x: 8.0
    y: 0.0
    z: 0.6

  total_time: 8.0
  use_wheels_motion_constraint: false
  traction_limit: 30.0

SlopePlat:
# 45 up, 63 down: 3.2, 0.4, 7.0, 400, shift, ff
# 63 up, 45 down: 3.2, 0.4, 7.0, 400, shift, ff
# 45 up, 45 down: 1.8, 0.65, 4.2, 400, shift, ff (slow)
# 45 up, 45 down: 1.8, 0.65, 3.2, 400, shift, ff (fast)
# 65 up, 45 down: 1.7, 0.65, 4.2, 400, shift, ff (slow)

  initial_pose:
    x: 0.0 # 3.0
    y: 0.0
    z: 0.45 #0.41
   
  final_pose: 
    x: 1.7 # -3.2
    y: 0.0
    z: 0.62

  total_time: 5.0 #3.5
  use_wheels_motion_constraint: false
  traction_limit: 400.0

Slope:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.4
   
  final_pose: 
    x: 3.0
    y: 0.0
    z: 0.4

  total_time: 3.5
  use_wheels_motion_constraint: false
  traction_limit: 400.0

Gap:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.95
   
  final_pose: 
    x: 3.5
    y: 0.0
    z: 0.95

  total_time: 3.0
  use_wheels_motion_constraint: false
  traction_limit: 400.0

TwoSlope:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 3.0
    y: 0.0
    z: 0.5

  total_time: 3.5 #4.0
  use_wheels_motion_constraint: false
  traction_limit: 300.0 #300.0

MultipleSlopes:
# 45 up, 63 down: 3.2, 0.5, 6.8, 400, shift, ff
# 63 up, 45 down: 3.2, 0.5, 6.8, 400, shift, ff
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 1.8
    y: 0.0
    z: 0.45

  total_time: 4.0 #6.8
  use_wheels_motion_constraint: false
  traction_limit: 400.0

TwoStep:
  initial_pose:
    x: 0.0
    y: 0.0
    z: 0.5
   
  final_pose: 
    x: 2.2
    y: 0.0
    z: 0.8

  total_time: 3.6 #3.6 #4.1 #4.0
  use_wheels_motion_constraint: false
  traction_limit: 400.0 #300.0

use_non_holonomic_constraint: false







